[package]
name = "helio-cloudinit"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.11.5"

helio-pg = { path = "../helio-pg" }
chrono = { version = "0.4.38", features = ["serde"] }