[package]
name = "helio-pg"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
diesel = { version = "2.2.0", features = ["chrono", "postgres", "r2d2", "serde_json"] }
chrono = { version = "0.4.38", features = ["serde"] }